//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.Bill_Modification = new HashSet<Bill_Modification>();
        }
    
        public int Bill_ID { get; set; }
        public int Order_ID { get; set; }
        public System.DateTime Created_Date { get; set; }
        public float Total_Price { get; set; }
        public string Responsible_Man { get; set; }
        public Nullable<System.DateTime> Delivered_Date { get; set; }
        public Nullable<System.DateTime> Received_Date { get; set; }
        public Nullable<bool> Cancelled_Bill { get; set; }
        public string Reason_Cancel { get; set; }
        public string Shipper_ID { get; set; }
        public string Reciever_Name { get; set; }
        public string Reciever_Phone { get; set; }
        public string Reciever_Addresss { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee_Account Employee_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_Modification> Bill_Modification { get; set; }
        public virtual Order_Details Order_Details { get; set; }
    }
}
