//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_Details()
        {
            this.Bill = new HashSet<Bill>();
            this.Order_Modification = new HashSet<Order_Modification>();
            this.Product_Order_Details = new HashSet<Product_Order_Details>();
        }
    
        public int Order_ID { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Ordered_Date { get; set; }
        public bool Delivered { get; set; }
        public Nullable<bool> Cancelled_Order { get; set; }
        public string Reason_Cancel { get; set; }
        public string Order_Name { get; set; }
        public string Exact_Address { get; set; }
        public string Order_Phone { get; set; }
        public Nullable<int> Province_ID { get; set; }
        public Nullable<int> District_ID { get; set; }
        public Nullable<int> Town_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bill { get; set; }
        public virtual District District { get; set; }
        public virtual Province Province { get; set; }
        public virtual Town Town { get; set; }
        public virtual User_Account User_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Modification> Order_Modification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Order_Details> Product_Order_Details { get; set; }
    }
}
