//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Order_Details
    {
        public int Product_ID { get; set; }
        public int Order_ID { get; set; }
        public int Order_Quantity { get; set; }
        public float Price { get; set; }
        public Nullable<int> Discount_Percent { get; set; }
        public string Promotion_Description { get; set; }
    
        public virtual Order_Details Order_Details { get; set; }
        public virtual Product Product { get; set; }
    }
}
