//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Image = new HashSet<Image>();
            this.Product_Modification = new HashSet<Product_Modification>();
            this.Product_Order_Details = new HashSet<Product_Order_Details>();
            this.Promotion = new HashSet<Promotion>();
        }
    
        public int Product_ID { get; set; }
        public int Catalogue_ID { get; set; }
        public bool Is_Sale { get; set; }
        public string Product_Name { get; set; }
        public float Price { get; set; }
        public int Level_Trending { get; set; }
        public string Description { get; set; }
        public Nullable<int> Products_Available { get; set; }
        public Nullable<int> Total_Sold { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Created_Username { get; set; }
        public string Guarantee_Description { get; set; }
        public string Title_Image { get; set; }
        public Nullable<float> Tax_Percent { get; set; }
        public string Manufacturer { get; set; }
    
        public virtual Catalogue Catalogue { get; set; }
        public virtual Employee_Account Employee_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Modification> Product_Modification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Order_Details> Product_Order_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promotion> Promotion { get; set; }
    }
}
