//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public int Promotion_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public string Promotion_Description { get; set; }
        public Nullable<int> Discount_Percent { get; set; }
        public Nullable<System.DateTime> From_Date { get; set; }
        public Nullable<System.DateTime> To_Date { get; set; }
        public Nullable<bool> Enable { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
